# Site settings
title: IP Geo Block
description: A WordPress plugin that will blocks any comment, pingback and 
 trackback spams posted from outside your nation.
 And it will also protect against malicious  access to the login form, admin 
 area and XML-RPC from undesired countries.

author: tokkonopapa
email: tokkonopapa@yahoo.com

# the subpath of your site, e.g. /blog
baseurl: "/WordPress-IP-Geo-Block"
url: "https://github.com/tokkonopapa/WordPress-IP-Geo-Block"

exclude: [README.md]

project:
  name: "Wordpress-ip-geo-block"

twitter_username: tokkonoPapa
github_username:  tokkonopapa

# Build settings
highlight: pygments
markdown: redcarpet

# extensions for GitHub Flavored Markdown
# pygments:
#   options: ["startinline"]
redcarpet:
  extensions: [
    "no_intra_emphasis",            # not apply em to foo_bar_baz
    "tables",                       # enable tables
    "fenced_code_blocks",           # enable ```
    "autolink",                     # enable auto link
    "disable_indented_code_blocks", # disable code block with spaces
    "strikethrough",                # del tag with ~~
    "superscript"                   # use sup ex: 2^n
  ]

excerpt_separator: "<!--more-->"
