# Site settings
title: IP Geo Block
description: A WordPress Geo-blocking plugin with Zero-day Exploit Prevention
#A WordPress plugin that will blocks any comment, pingback and 
# trackback spams posted from outside your nation.
# And it will also protect against malicious access to the login form, admin 
# area and XML-RPC from undesired countries with zero-day exploit prevention.

author: tokkonopapa
email: tokkonopapa@yahoo.com

# the subpath of your site, e.g. /blog
# baseurl: "/WordPress-IP-Geo-Block"
# url: "http://tokkonopapa.github.io/WordPress-IP-Geo-Block"

# for local: jekyll serve --drafts --baseurl
baseurl: "http://www.ipgeoblock.com"
url: ""

permalink: none

# Paginate
recent_post: 5
paginate: 5
paginate_path: "/:num/"

exclude: [README.md]

project:
  name: "Wordpress-ip-geo-block"

excerpt_separator: "<!--more-->"

# Build settings
highlight: pygments
markdown: redcarpet # kramdown

# extensions for GitHub Flavored Markdown
# pygments:
#   options: ["startinline"]
redcarpet:
  extensions: [
    "no_intra_emphasis",            # not apply em to foo_bar_baz
    "tables",                       # enable tables
    "fenced_code_blocks",           # enable ```
    "autolink",                     # enable auto link
    "disable_indented_code_blocks", # disable code block with spaces
    "strikethrough",                # del tag with ~~
    "superscript"                   # use sup ex: 2^n
  ]

kramdown:
  input: GFM

# Google Analytics
# tokkonopapa@gmail.com
google_analytics_tracking_id: UA-42366765-2 

twitter_username: tokkonoPapa
github_username:  tokkonopapa

# Codex
collections:
  codex:
    output: true
